//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginDatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableAction
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int LocaleId { get; set; }
        public int CustomerTypeId { get; set; }
        public int ActionTypeId { get; set; }
        public int ActionCode { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual Locale Locale { get; set; }
    }
}
